### ISSUE TITLE
Test steps not sorted correctly?

### ISSUE THREAD

**Issue by steve-bate** [fediverse-devnet/feditest#107]
`inspect.getmembers`:

> Return all members of an object as (name, value) pairs sorted by name

I'm assuming you want the steps in the order they are defined in the Test class.

**Comment by steve-bate** [comment]
As a followup question, what's the intent for the test "steps" (vs calling the step methods from a test method)?

**Comment by jernst** [comment]
On your question: worth writing an FAQ entry, hope this clarifies: https://feditest.org/docs/faq-feditest/test-functions-classes-steps/

**Comment by steve-bate** [comment]
> On your question: worth writing an FAQ entry, hope this clarifies: https://feditest.org/docs/faq-feditest/test-functions-classes-steps/

Thanks for the FAQ entry. I think I understand. It supports a type of customized interactive debugging. For my own development, I’ve used the Python debugger for that, but it doesn’t support unwinding state to return to previous statements. I’ll be interested is seeing how this is done with feditest.
