### ISSUE TITLE
Can you clarify "disabled" vs "skipped"?

### ISSUE THREAD

**Issue by steve-bate** [fediverse-devnet/feditest#116]
It looks like disabled doesn't count as skipped now. Is "skipped" only related to "non-implementation"? Or?

**Comment by jernst** [comment]
I think we have several cases:

1. A `Node` doesn't implement a certain method, so some test(s) cannot be run. Those should be reported in a separate category from pass and fail.
2. A test is (temporarily?) marked as "skip this for now" by the user. (Alternatively it could be removed from the test plan.)
3. A TestRun is executed with ``--interactive`` and the user decided to interactively skip a test or step. This may happen if they repeatedly execute some other tests or steps for interactive debugging purposes. Interactive running is particularly useful if setting up the constellation was expensive and the user wants to keep running the same test without restarting the constellation yet.

Perhaps the second and third case can be reported together. Not sure. In any case, the categories need more comprehensible names!

**Comment by steve-bate** [comment]
Thanks. Does "disabled" mean the test should not be run in any case? If so, should we not include those in the test report (or even include them in the test plan)?

**Comment by jernst** [comment]
idk. I wanted to see when we are actually running into this and then decide what's the most logical thing to do.
