### ISSUE TITLE
In reports, show app version in addition

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#128]
So we need to ask our `Node` which app and what version it is.

**Comment by jernst** [comment]
To do this, we need to also save the `TestRunConstellation` into the `TestRunTranscript`. That lets us ask the actual `Nodes` for the name and version of the applications they are running.

**Comment by jernst** [comment]
The Imp does that now, as do the sandbox client and servers. The rest doesn't know what it is running.

**Comment by steve-bate** [comment]
For AP Fediverse Webfinger, since the implementation is typically combined with an AP implementation, feditest could query nodeinfo (if available) to determine the software version (and name). This could be built into the SaaS node driver.
