### ISSUE TITLE
WebFinger Report Suggestions

### ISSUE THREAD

**Issue by steve-bate** [fediverse-devnet/feditest#130]
If I imagine myself as a consumer of this report, these are the suggestions I'd have for improving the report format. Overall, my objective is to be able to consume the report information with maximal "signal to noise ratio" and minimal effort.

Note that these comments are for the WebFinger report. It's possible that we'll have a slightly different report template for AP/Fediverse test reports.

### Suggestion: Use implementation names for the test matrix column headings.

The "Session n" heading provides no useful information to me. I'd like to see the name of the implementation that's a link to the session details. I don't want to click each heading to investigate which implementation it is.

### Suggestion: Remove the node driver class names from the text matrix column headings.

As a WebFinger report consumer, I don't care about those in that context. If I need that information, I'll drill down into the session details.

### Suggestion: Find a better way to label failures in the test matrix

The current approach of using the exception name is less useful, in my opinion, than just a "failed" label. I see "AssertionError" and "HardAssertionFailure" and I don't know what that is telling me without expanding the cell. It's just extra noise. There are two primary types of failures in WebFinger test suite: bad HTTP status and missing CORs header. Maybe we could use a short label for those in the cell (e.g., "Wrong HTTP status", "Missing CORS header"). 

### Suggestion: Remove the malformed URI tests

Since it's effectively impossible to pass them. That's a spec issue, not an implementation issue *per se*.

### Suggestion: Avoid floating right.

On a desktop, especially with large monitors and a wide browser window, it's more work to scan to the far right to see information since (in the west) we tend to read left-to-right. If that information is not valuable, then fine. But in this case, I think that's probably not the case (the feditest link, for example). If the metadata flowed on the left (maybe just to the right of the test summary), then the timestamp in the report title isn't needed since it can be found easily in the metadata table.

### Suggestion: Minimize table borders

I understand this is an artistic/aesthetic consideration, but for me, the table borders are mostly visual noise that I need to dig through to find the information I want.

**Comment by jernst** [comment]
See also #89 which I'm working on.

**Comment by steve-bate** [comment]
It might also be useful to show a % pass, or an equivalent visual indicator, for each column in the test result matrix and for each row (to see how common a given test passes or fails across the set of servers).

**Comment by steve-bate** [comment]
### Suggestion: Human-friendly test names

The test names are diffficult to read and have a lot repeated information (e.g., the "webfinger.server" prefix). Maybe we could use a decorator to provide a human-friendly name for the test?

**Comment by steve-bate** [comment]
### Suggestion: Don't inline expanded error messages in the test matrix cells

With the fully expanded messages in the text matrix, I need to vertically scroll down to horizontally scroll the table and then vertically scroll back up to see which columns are visible. This is with a reasonably large monitor (32"). There are at least a couple possible solutions. One is to use a short name for the type of failure in the text matrix cells ("HTTP Status" or "No CORS Header" or "Wrong Content Type" that can be expanded to see the details). This would keep the matrix more vertically-compact. However, if we have a large number of tests, there would still be the same issue with the table height. We could also duplicate the headers at the bottom of the matrix for horizontal scrolling purposes (even with the verbose error messages in the cells).

**Comment by jernst** [comment]
Re matrix test column headings, I'm now using the constellation name, and in case of Imp-vs-X we can simply use X (and the constellation generation scripts do that now). But it's more complicated if we test application X against Y (e.g. Mastodon vs WordPress). For that, we need to list both apps, and the sequence is important too.

Re Node Driver in column: done.

Re failure labeling in the test matrix: Created separate issue #139

Re malformed URI tests, which specific tests would you like to remove?

Re floats: gone.

Re borders: replaced with something hopefully less offensive :-)

Re human-friendly test names: I'd prefer to keep the identifiers (which are now line breaking) and inline the description of the test. Separate issue #140

Re inline expanded error messages: removed, and see #139.

Can we close this and have separate issues for whatever remains of this list?

**Comment by steve-bate** [comment]
I'll close this and follow up on, or create, separate issues. Thanks.
