### ISSUE TITLE
Annotate the webfinger tests with descriptions

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#140]
... so the descriptions show up in the reports, not just the test identifiers.

**Comment by steve-bate** [comment]
Do you thinking of something along the lines of using `__doc__` strings?

```python
@test
def test_something():
    """This is a description of a test of something."""
   # The test
```

**Comment by jernst** [comment]
That's already working in the sandbox, e.g. the docstrings from https://github.com/fediverse-devnet/feditest-tests-sandbox/blob/develop/tests/sandbox/example_test_with_functions.py show up in the report.

**Comment by steve-bate** [comment]
Great!
