### ISSUE TITLE
Test Matrix Report: Collapsed error descriptions in test matrix.

### ISSUE THREAD

**Issue by steve-bate** [fediverse-devnet/feditest#143]
To clarify my earlier comment, I didn't think it would work well to unconditionally display full test failure descriptions in the test matrix cells. However, I do think it's useful to have collapsed failure/error descriptions that can be expanded, where desired (for the test matrix audience). I think it's even more useful if the collapsed descriptions have a very terse description of the type of failure .

![image](https://github.com/fediverse-devnet/feditest/assets/789524/712c965f-e5f7-4cff-af81-147922de1b49)

See also: #139

**Comment by jernst** [comment]
Superseded by #173.
