### ISSUE TITLE
Reporting: Skipped Test

### ISSUE THREAD

**Issue by steve-bate** [fediverse-devnet/feditest#146]
Was the `parameter_ordering` test skipped mostly for report generation testing purposes? It seems like a test like this shouldn't be included in the report. It makes sense that a Node might raise this exception, but we should require a description/reason for skipping (maybe it's a bug, maybe it's intentional, ...). 

In the future, the framework might skip tests if we have a capabilities model, the test is associated with required capabilities, and we know the server(s) being tested don't have that capability.

**Comment by jernst** [comment]
The `parameter_ordering` test being not fleshed out was just me being lazy. Sorry.

Also https://github.com/fediverse-devnet/feditest/pull/151
