### ISSUE TITLE
Test Matrix Report: metadata?

### ISSUE THREAD

**Issue by steve-bate** [fediverse-devnet/feditest#147]
Was the test metadata removed from the report? I think that could be useful, but I can understand if we put it after the matrix data since that's the primary information in the report. If we add it back, I'd like to see the test run duration (vs just start and end times) along with the other metadata.

**Comment by jernst** [comment]
Right now we have this.
![Screenshot 2024-05-25 at 11 35 17](https://github.com/fediverse-devnet/feditest/assets/874785/0ad36312-da62-44ce-8c30-9f56914e227c)

I have removed hostname and username from the default generation -- for public reports neither is necessarily/desirable IMHO. But they are added back in with `feditest run --who`.

What else do we need?
