### ISSUE TITLE
Report on NodeDriver errors

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#188]
E.g. if a NodeDriver cannot instantiate a Node on this OS, report on that in the report.

**Comment by steve-bate** [comment]
What currently happens in this scenario?

**Comment by jernst** [comment]
It gets written to the console, but doesn't show up in the report I think. So if somebody ran tests from cron or such, and only looked at the final HTML results, they might at best be very confused and at worst not realize something bad happened.

**Comment by steve-bate** [comment]
> It gets written to the console, but doesn't show up in the report I think. So if somebody ran tests from cron or such, and only looked at the final HTML results, they might at best be very confused and at worst not realize something bad happened.

So an error message is written to stdout/stderr but no exception is thrown?

**Comment by jernst** [comment]
I think we should always throw exceptions when error occur, and make sure all exceptions show up in the reports if any report is being generated at all.
