### ISSUE TITLE
Generate anchors for each meaningful test result

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#202]
So somebody reading a test report can copy-paste the URL to that specific test result and share it with somebody. "I want you to fix **this** problem".

**Comment by jernst** [comment]
If the link goes to a cell inside a table, it's hard to tell which cell if all we do is `<td id="something">`. It would be nice to highlight the specific cell when the browser URL has fragment `#something`.

No idea how to do this. Ideas, anybody?

**Comment by jernst** [comment]
It seems https://developer.mozilla.org/en-US/docs/Web/CSS/:target is just the ideal solution here. Thanks  @Ryuno-Ki!

**Comment by steve-bate** [comment]
If I had a link to a test result, I'd prefer the link was to the detailed test result data rather than the table cell.

**Comment by jernst** [comment]
It should be both IMHO. The use case is: "Whatever I am looking at, I should be able to share it with somebody".

**Comment by jernst** [comment]
Maybe there are two requirements:
* The telephone use case: "Hey Joe, I'm looking at *this thing*, I text you the URL, please look at it, too, what do you think of that?"
* "I'm looking at the summary of a failed test in the Matrix, and I want to know details. So I want to click on the Matrix cell to see the details in the session report."

**Comment by jernst** [comment]
This touches some of the same files I just moved, so I will hold off on editing until the previous PR is merged.

**Comment by jernst** [comment]
Fixed
