### ISSUE TITLE
Eliminate test result "shadowing" in results

### ISSUE THREAD

**Issue by steve-bate** [fediverse-devnet/feditest#235]
We have tests that fail for reasons unrelated to the test. For example, a content type test might fail because there is a nonstandard key in the JRD although the content type is actually correct. In the past, we've seen similar issues with incorrect content-type shadowing other test results. I haven't reviewed the latest test reports for examples, but developers are reporting this as an issue (Friendica dev, for example).

I think the primary cause of this issue is not considering the "Imp" as a test fixture (client test stub) and having it do result validation (a different form of testing) instead of leaving the testing to the tests.

**Comment by mexon** [comment]
FWIW, in fact this problem is not shadowing any other problems in Friendica.  When I remove that strict checking, and with recent fixes to Friendica, it gets a perfect score 😇  However, that's just a coincidence.  The issue certainly does have the potential to shadow other problems.

**Comment by jernst** [comment]
I want to look at this again, but not right this instant. Which test would be a good example for this?

**Comment by mexon** [comment]
As I said above, Friendica currently (in develop branch) gets a perfect score apart from the invalid URI schemes.  So I introduced an artificial issue.  Friendica ignores the `rel` parameter.  It's entirely conceivable it might not handle it.  So I pretended it was broken like this:

			if (!empty($_GET['rel'])) {
				throw new BadRequestException();
			}

Running the tests with or without this problem fails the following tests:

* `webfinger.server.4_1__2_parameter_ordering_not_significant::parameter_ordering`
* `webfinger.server.4_2__2_perform_query::normal_query`
* `webfinger.server.4__1_accepts_all_link_rels_in_query::accepts_combined_link_rels_in_query`
* `webfinger.server.4__1_accepts_all_link_rels_in_query::accepts_known_link_rels_in_query`
* `webfinger.server.4__1_accepts_all_link_rels_in_query::accepts_unknown_link_rels_in_query`

If I then remove the `Link rel value not absolute URI nor registered relation type` from Feditest and run again, `webfinger.server.4_2__2_perform_query::normal_query` works, but all the remaining four still fail.  If I remove the artificial breakage of `rel` parameters, all tests pass.  So a problem with `rel` parameters is being "shadowed" by an unrelated issue with URI schemes.

**Comment by jernst** [comment]
This was rewritten. Closing, can re-open if it happens again.
