### ISSUE TITLE
NodeDriver naming

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#239]
On `develop`, we now have:

```
% feditest list-nodedrivers
imp.ImpInProcessNodeDriver
manual.ManualFediverseNodeDriver
mastodon.manual.MastodonManualNodeDriver
mastodon.ubos.MastodonUbosNodeDriver
saas.SaasFediverseNodeDriver
sandbox.SandboxMultClientDriver_ImplementationA
sandbox.SandboxMultServerDriver_Implementation1
sandbox.SandboxMultServerDriver_Implementation2Faulty
wordpress.WordPressPlusActivityPubPluginUbosNodeDriver
```

which isn't internally consistent: the Mastodon ones have an extra package, and they repeat themselves: eg "manual" is in the name twice. Also the `feditest-tests-fediverse` Makefiles don't run any more due to this change.

The names of these drivers is part of the "UX" for feditest, and so it's worth pondering what's the most easily usable. 

I'm not enough of a Python hacker to figure out whether there is a way to keep the classes in the files they are in, while exporting them with a different name (and still using the `@nodedriver` annotation).

**Comment by steve-bate** [comment]
@jernst 

I'm back. I'll take a look at this but I don't have a good understanding of the problem yet.

> ```
> % feditest list-nodedrivers
> ...
> manual.ManualFediverseNodeDriver
> mastodon.manual.MastodonManualNodeDriver
> mastodon.ubos.MastodonUbosNodeDriver
> ...
> ```
> 
> which isn't internally consistent: the Mastodon ones have an extra package, and they repeat themselves: eg "manual" is in the name twice. 

That was already the case with `manual.ManualFediverseNodeDriver`, right? I'll need to study the node driver plugin implementation to determine why the extra module level in the path is a problem. That constraint is surprising to me.

> Also the `feditest-tests-fediverse` Makefiles don't run any more due to this change.

I tested with `feditest` directly and I thought it was working. Can you describe the steps for reproducing the Makefile problem?

> The names of these drivers is part of the "UX" for feditest, and so it's worth pondering what's the most easily usable.

Do you think the extra module entry in the path is a significant UX/DX/usability issue?

> I'm not enough of a Python hacker to figure out whether there is a way to keep the classes in the files they are in, while exporting them with a different name (and still using the `@nodedriver` annotation).

I may have suggestions after I study the node driver plugin discovery code further.

**Comment by jernst** [comment]
I'm in the middle of making the `Node` and `NodeDriver` hierarchy simpler, and it impacts this. See also #250

**Comment by jernst** [comment]
This is done with #252.
