### ISSUE TITLE
Add pre-commit hooks?

### ISSUE THREAD

**Issue by steve-bate** [fediverse-devnet/feditest#259]
What's your opinion on adding pre-commit hooks to run unit tests and do other processing before a commit (like formatting, linting, etc.).

There's a Python package that provides support for it. I've found it to be useful on other projects for maintaining code quality. I can set it up if we agree it would be useful here.

Another pre-commit action I've found useful is preventing commits if there is a NO_COMMIT comment in the code. That way I can do experimentation and know that I'll be reminded that I want to delete specific code before a commit.

**Comment by jernst** [comment]
Not opposed, but perhaps the better place would be before merge into `develop` and `main`? Could we get Github actions to do something like that?

**Comment by steve-bate** [comment]
> Not opposed, but perhaps the better place would be before merge into `develop` and `main`? Could we get Github actions to do something like that?

I assume something similar could be done with GitHub actions run on PRs, but I'd need to investigate. It's nice to have something developers can use locally (without requiring GitHub) prior to commit/push. Otherwise, they would need to push commits for the checks to be run.

**Comment by jernst** [comment]
Can it be the same in both places? With a way of skipping the local one for local-only checkins half-way through a refactor, for example?

**Comment by steve-bate** [comment]
> Can it be the same in both places? With a way of skipping the local one for local-only checkins half-way through a refactor, for example?

You can use the `git commit ... --no-verify` option to opt-out of pre-commit checks. You can also explicitly run the pre-commit checks at any time prior to commit.

**Comment by steve-bate** [comment]
The `pre-commit` also supports hooking into the `pre-push` event. That might be a better fit for your workflow.

https://[pre-commit](https://pre-commit.com/#advanced).com/#advanced

**Comment by jernst** [comment]
Would you like to take a stab at what you have in mind there @steve-bate ?
