### ISSUE TITLE
Mastodon: create application

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#261]
In the constructor of `NodeWithMastodonAPI`, use something like:

```
(client_id, client_secret) = Mastodon.create_app(
    'feditest',
    scopes=['read', 'write', 'follow', 'push'],
    redirect_uris=None,
    website='https://feditest.org/',
    api_base_url='https://{ hostname }/',
    user_agent='feditest')
```
and store those two values there. This merely registers `feditest` as a client app.

Reference: https://mastodonpy.readthedocs.io/en/stable/04_auth.html#app-registration-and-information

It seems to implement the first request in https://docs.joinmastodon.org/client/token/#app

**Comment by steve-bate** [comment]
Just curious, was there a specific problem that motivated this? I was able to do the Follow test without registering feditest as a client (just using the Bearer token).

**Comment by jernst** [comment]
I would like to automate obtaining the Bearer token.

**Comment by jernst** [comment]
Done, but incorrectly per #276. Closing this as that one is good enough.
