### ISSUE TITLE
Mastodon: create a bearer token for a specific user

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#263]
Apparently, the Mastodon API can be used as

1. a client application without being a specific user. That is described in https://docs.joinmastodon.org/client/token/#flow
2. a client application that has specific permissions granted by a particular user. That is described in https://docs.joinmastodon.org/client/authorized/#login

Best I can tell those produce different bearer tokens. (If my client wanted to act on behalf of 5 users, does it need 5 separate tokens? Am I misunderstanding something here?) 

The second item is apparently what the second code section here does: https://mastodonpy.readthedocs.io/en/stable/ , see also https://mastodonpy.readthedocs.io/en/stable/_modules/mastodon/authentication.html#Mastodon.log_in

So we want that second invocation every time the test code wants to obtain a new `Actor`, which should happen right after the code from #262 has run.

We know the username and password because we created the new username per #262 and Mastodon printed out the password as a result of the `tootctl` invocation. We should "clone" the `Mastodon` object from `mastodon.py` and have one instance per live Actor that is stored in the `Node`. No need to write anything to disk.

**Comment by steve-bate** [comment]
For 1, isn't the client id and secret specific to a account/user? When creating the application, a login would have been required to select authorizations (scopes) for the application. 

> If my client wanted to act on behalf of 5 users, does it need 5 separate tokens

I believe that's true. 

However, I see a `superapp` column in the Mastodon `oauth_applications` database table. I'm not sure what that means. It seems to bypass authorizations (?) but still appears to be user-specific. I don't see a way to set that flag from an API call. It seems to be initialized when the database is created and only applies to the built-in web application.

> We should "clone" the Mastodon object from mastodon.py and have one instance per live Actor that is stored in the Node.

Other than the "cloning" part, isn't that what the node already does? (Unless it's been modified recently... I'll take a look.) Each actor associated with the node should have its own `api` instance configured with its access token.

**Comment by jernst** [comment]
> For 1, isn't the client id and secret specific to a account/user? When creating the application, a login would have been required to select authorizations (scopes) for the application.

The first two `curl` operations in https://docs.joinmastodon.org/client/token/#flow do not use any account information. When I followed these instructions, I could use the API, but not access any data that's confidential for a particular user. The `Mastodon.py` library appears to only support the second scenario.

> ...isn't that what the node already does?

Yes, I was reviewing APIs and protocols and not looking at the code when writing this down.

**Comment by steve-bate** [comment]
> The first two `curl` operations in https://docs.joinmastodon.org/client/token/#flow do not use any account information. When I followed these instructions, I could use the API, but not access any data that's confidential for a particular user. The `Mastodon.py` library appears to only support the second scenario.

Interesting. How did you get a `client_id` and `client_secret` for that first API call?

**Comment by jernst** [comment]
> How did you get a client_id and client_secret for that first API call?

Oops, my link should not have included the #flow anchor. The call before that ("Create our application") produces those two values.

**Comment by steve-bate** [comment]
> The call before that ("Create our application") produces those two values.

Ah, ok. I didn't know that could be done without triggering user authentication. Now I'm curious about the benefits of that kind of token.

> I followed these instructions, I could use the API, but not access any data that's confidential for a particular user

What are some examples of API calls can you access with this user-independent token that you couldn't access without it? The public API calls typically don't require an API token (`/api/v1/instance`, for example).

**Comment by jernst** [comment]
I'm not certain. I just followed the sequence of calls on that page ...

**Comment by jernst** [comment]
Done in #252, and there are already follow-on issues, so closing
