### ISSUE TITLE
Cleanly distinguish between Node interfaces and default implementations

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#273]
Python doesn't give us any direct way of capturing this, but it should be captured because otherwise it confuses us and everybody:

There are really three categories of the Python classes starting with `Node` as the top-most class and including all of its subclasses.

1. Abstract interfaces (in the Java sense) that define the communication between FediTest tests and the `Nodes` they interact with. All of the methods in those abstract interfaces should be abstract.
2. Partial implementations of these abstract interfaces. They are partial for two reasons:
  a) Some collect some code that is likely going to be the same for all subclasses, so we define it here for convenience purposes. While they may be overridden in subclasses, that's unlikely.
  b) Some have default implementations, mostly asking the user for input, so that developers do not need to write concrete subclasses (the next and last category) before being able to do something. All of those should/must be overridden eventually when the `Node` implementation is complete for a given application.
3. At the bottom: concrete implementations that, for example, implement all the methods of `FediverseNode` for a locally-running Mastodon instance on UBOS.

The distinctions become particularly clear when thinking of `Node` implementations that run remotely and are accessed via something like JSON-RPC or CORBA (RIP :-)). Which should be the default way we think about this. In this arrangement, categories 2 and 3 all run on the remote Node, while FediTest only as the abstract interfaces (and a "client-to-RPC-mapping" implementation that connect them to the RPC tech). Category 2b does not exist at all, and remote category 3 may use 2a for convenience reasons but might likely not (e.g. when a different language is involved).

So, this is a long-winded way of saying: Rename / refactor all of those classes that that these category distinctions are readily apparent.

**Comment by steve-bate** [comment]
Something else to consider (that isn't an option with Java) is `typing.Protocol`. A `typing.Protocol` defines a duck-typed shape for a type. Nothing needs to implement this type, but it is used as a type hint for variable typing, function arguments and so on. There are several tradeoffs between this approach and using the `ABC` abstract base classes. The `typing.Protocol` technique can be used to static type checking vs relying on the exceptions raised at runtime by ABC. However, both techniques can be used together.

```python
class Node(typing.Protocol):
    def method1(self, arg1: str):
       """The method to do something"""

    def method2(self, somearg: int): ...


class AbstractNode(ABC):
    @abstractmethod
    def method1(self, arg1: str): ...

    @abstractmethod
    def method2(self, somearg: int): ...

class SomeSpecificNode(AbstractNode):
  ....

def some_function_that_uses_node(node: Node):
    node.method1("foo")  # can be statically type-checked
```
