### ISSUE TITLE
Mastodon Node: `_local_users_by_userid` not populated?

### ISSUE THREAD

**Issue by steve-bate** [fediverse-devnet/feditest#277]
I see it initialized to an empty `dict`, but then later, in `_get_mastodon_client_by_actor_uri`, there is code retrieve a `UserRecord`...

```python
        user = self._local_users_by_userid.get(userid)
        if not user:
            raise ValueError(f'Cannot find user { userid }')
```

However, I don't see where `_local_users_by_userid` is populated with a `UserRecord`.

**Comment by jernst** [comment]
Obsolete now due to #333.
