### ISSUE TITLE
Mastodon Node: incorrect data type for retry arguments.

### ISSUE THREAD

**Issue by steve-bate** [fediverse-devnet/feditest#279]
```python
    def wait_for_object_in_inbox(self, actor_uri: str, object_uri: str) -> str:
# ...
        response = self._poll_until_result( # may throw
#...
            cast(int,self.parameter('inbox_wait_retry_count', '5')),
            cast(int, self.parameter('inbox_wait_retry_interval', '1')),
```

The `cast` doesn't convert the string default value to an int. It's just a type hint override. The `parameter` return value will need to be converted to an `int` (`int(value)`).

**Comment by jernst** [comment]
James Gosling, a long time ago, stated his principle that a programming language should be really easy to read. Nobody should ever have to guess what something might mean, and guess wrong half of the time. I've always very much agreed with that principle. There are clearly worse offenders than Python but ...
