### ISSUE TITLE
Mastodon Node: allow access token to be explicitly configured.

### ISSUE THREAD

**Issue by steve-bate** [fediverse-devnet/feditest#281]
This could make testing easier for non-UBOS server deployments.

**Comment by jernst** [comment]
You are right.

**Comment by jernst** [comment]
This should work now with accounts specified in the node section of the test plan with:

```
{
    "nodedriver" : ...
    "accounts" : [
        {
            "userid" : ....
             "oauth_token" : TOKEN
        }
    ]
}
```

See, for example, `feditest info --nodedriver MastodonSaasNodeDriver`.

However, this has not been tested so far so I leave this open.

**Comment by jernst** [comment]
@steve-bate could you test that this works with your setup.

**Comment by jernst** [comment]
Closing this as I believe it is done.
