### ISSUE TITLE
WordPress Node: Strip trailing slash in `_actor_uri_to_userid`.

### ISSUE THREAD

**Issue by steve-bate** [fediverse-devnet/feditest#283]
At least in my WordPress installation the URI is required to have a trailing slash and that ends up being included in the userid with the current Wordpress method override.

Related: #275

**Comment by jernst** [comment]
Suggest we make this work this way first, and once we have something running, we think again.

**Comment by steve-bate** [comment]
> Suggest we make this work this way first, and once we have something running, we think again.

I'm not sure what you mean. We can't make the URL work with WordPress without the trailing slash.

Are you referring to the hard-coded URL structures rather than specifically to the trailing slash?

**Comment by jernst** [comment]
I typed this comment into the wrong issue, was intended for #275. Too many windows open.

**Comment by jernst** [comment]
This does not seem to be an issue any more based on looking at the code.
