### ISSUE TITLE
Settle on minimum Python version

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#307]
Let's first collect what versions we are all run on which OSs.

As of 2024-08-14:

* macOS Apple Silicon:
  * `/opt/homebrew/bin/python3 --version`: 3.12.5
  * venv after `make build PYTHON=python3`:  3.12.5

* macOS Intel:
  * `/opt/homebrew/bin/python3 --version`: 3.12.5
  * venv after `make build PYTHON=python3`:  3.12.5

* Arch Linux x86_64:
  * https://archlinux.org/packages/core-testing/x86_64/python/ : 3.12.5

* Arch Linux aarch64:
  * https://archlinuxarm.org/packages/aarch64/python: 3.12.4

* Windows:
  * https://www.python.org/downloads/windows/: 3.12.5

* Ubuntu 22.04 LTS aarch64:
  * `python --version`: 3.10.12
  * `python3.11 --version`: 3.11.0rc1

Please add comments with what version you are running on which OS.

**Comment by jernst** [comment]
There's a line in `pyproject.toml`:
```
requires-python = ">=3.11"
```
I'm only guessing at what it might do.

**Comment by steve-bate** [comment]
Ah... so it should be compatible with 3.11.*. However, I just updated my venv to 3.12.5.

**Comment by mexon** [comment]
I nominate Raspberry Pi OS as an important platform.  Mine are mostly bullseye/debian 11 with Python 3.9.2, one or two bookworm/debian 12 with Python 3.11.2.  It's reasonable to tell me to upgrade to the latest stable version for doing testing.

**Comment by jernst** [comment]
You think many developers use the Pi as their development machine? When I asked around back in December, I don't think anybody mentioned that. (I do understand it as a production host, but development?)

**Comment by mexon** [comment]
My use case is testing ActivityPub servers on real hardware communicating over a real network.  I don't actually do that these days, I switched to Vagrant.  But I certainly do still want that as an option.  Another thing I don't do is keep the pis on an isolated network, so I could in principle use my development machine to run feditest (except that my development machine is Ubuntu 22.04 still, so I can't do that).  But that's also an important case I think.

Not that the distinction really matters though.  It's just Debian really.  And Debian certainly is an important developer platform.
