### ISSUE TITLE
Document/describe all setup variations that we intend to support

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#323]
We are talking about a few:

* here https://feditest.org/quickstart/evaluate/
* and here https://feditest.org/quickstart/fediverse-developer/

What others are there? Right now we just need to enumerate them, publishable documentation can come later.

**Comment by steve-bate** [comment]
It's a special case of https://feditest.org/quickstart/fediverse-developer/, but in addition to running on localhost (or another host on the local network), a developer may want to use a non-default port for the HTTP/HTTPS scheme. This could be useful if they are running multiple nodes on the same host or if the default port for the URL scheme is being used by something else on that host.

**Comment by jernst** [comment]
Other than non-standard port, in the same setup, do we want/need to support:
* http instead of https
* https without a valid trust chain
* https with a custom CA that's not part of the system trust store
* https with a custom CA that has been added to the system trust store
I assume we support https with an official cert

**Comment by jernst** [comment]
I think this is the simplest and at the same time most general approach: https://feditest.org/reference/howtos/run-application-locally-nonstandard-port/
