### ISSUE TITLE
test_mastodon_node.py methods

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#326]
There are a few methods used in `test_mastodon_node.py` that I can't find definitions for. E.g.
`node.delete_follows()`.

That `node` is supposedly a `MastodonManualNode`, which was eliminated in favor of `NodeWithMastodonAPI` and simply `MastodonNode` -- but they don't have those methods either and I don't remember that they ever did?

**Comment by steve-bate** [comment]
> There are a few methods used in `test_mastodon_node.py` that I can't find definitions for. E.g. `node.delete_follows()`.
> 
> That `node` is supposedly a `MastodonManualNode`, which was eliminated in favor of `NodeWithMastodonAPI` and simply `MastodonNode` -- but they don't have those methods either and I don't remember that they ever did?

Yes, they were previously there to help with test teardown.

**Comment by jernst** [comment]
I think I added them back in in the "Test support" section here: https://github.com/fediverse-devnet/feditest/blob/c4111b1c92cc48472ca537c9888acd1f41fa288c/src/feditest/nodedrivers/mastodon/__init__.py#L497

Please close this issue if that seems right.

**Comment by jernst** [comment]
I think we are done with this.
