### ISSUE TITLE
Cannot find NodeDriver "ImpInProcessNodeDriver"

### ISSUE THREAD

**Issue by naturzukunft** [fediverse-devnet/feditest#335]
Hi there, 
did (i hope so) the stuff described [here](https://feditest.org/quickstart/evaluate/).
And get the following error:

```
$ feditest run --testplan examples/testplans/webfinger-server-imp-vs-saas-any.json --html myapp-webfinger-results.html
2024-09-16T19:30:00Z [CRITICAL] feditest: <class 'feditest.testplan.TestPlanError'> -- TestPlan defined insufficiently: TestPlanSession 0: Role client: Cannot find NodeDriver "ImpInProcessNodeDriver".

$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.

```

**Comment by jernst** [comment]
We need to update our documentation. You are running on branch `develop` which has progressed quite a bit since we wrote the documentation for 0.3, and so the documentation is out of date w.r.t `develop` but still current (we think) w.r.t label `v0.3`.

Please `git checkout v0.3` and try again.

**Comment by jernst** [comment]
Updated docs: https://feditest.org/quickstart/evaluate/ 

@naturzukunft could you report back whether that solves the issue?

**Comment by naturzukunft** [comment]
Hi Johannes, it was already working with 
`git checkout v0.3`
Thanks!
