### ISSUE TITLE
Directory name conflict

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#337]
The FediTest convention is that our tests are collected from ``--testsdir ./tests`` by default.

The Pyunit convention is also collecting tests from there.

Currently when somebody runs `feditest` from the root of the `feditest` repo, FediTest attempts to collect fedi-tests from `./tests` and comes across the pyunit tests there. Hilarity ensues.

Asking the user not to do that is probably a bad idea, as is asking them to always specify ``--testsdir some/where/else``.

Seems one of them should be renamed: either the FediTest defaults ``--testsdir`` or the name of the directory that contains the FediTest unit tests in the `feditest` repo. 

Any opinion which @steve-bate ?

**Comment by jernst** [comment]
See also #338. We should fix both.

**Comment by steve-bate** [comment]
Put the unit tests in a directory `tests.unit` and modify the pyproject.toml to configure pytest to run tests from there.
