### ISSUE TITLE
Capture metadata for the fediverse server applications we want to test

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#34]
There may be all sorts of things that we want to capture, and we need to come up with a way to do this. This includes:

* Platforms on which the server application runs on.
* Whether it requires HTTPS to communicate with it, even during testing.
* Which "profiles" it supports, so we don't attempt to run tests that are known to fail. (How to define profiles is a separate issue.)
* Whether the server application will have certain behaviors or not. Example: a server application that is known to never create ephemeral objects (as defined in the AP spec) can and should be tested to always emit resolvable IDs.

**Comment by steve-bate** [comment]
I think we should move this back to the backlog for now. It's a bit of a catch-all task and it would be better to define more specific tasks to design and implement the various parts as we need them and the requirements are more clear. What do you think?

Some aspects of this will be covered in #46.

**Comment by jernst** [comment]
It occurs to me it may be better that the test runner executes whatever tests are defined in the active TestPlan.

But that test annotations and app annotations are used by a (to-be-created) TestPlanCreator to suggest sensible TestPlans -- which the user can then override as they like by editing the TestPlan.

**Comment by jernst** [comment]
Closing this, so far we haven't needed it and we have other mechanisms such as the `NotImplementedException`s
