### ISSUE TITLE
Clean up follow API

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#346]
Current method `make_a_follow_b` isn't cutting it. We need to distinguish between just sending the "follow" and then not responding, or confirming vs rejecting, and the various states that the exchange can be in over time.

Then, we need to update the Mastodon code which is currently partially commented-out due to that confusion.

**Comment by steve-bate** [comment]
The original code polled the API for a Relationship status to be established. I see that's commented out currently.
