### ISSUE TITLE
Find a way around SSRF protections by WordPress plus plugins

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#367]
It seems to be activated in `wp_safe_remote_get` in `wp-includes/http.php` and things like WebFinger lookup invoke this with the default arguments, which is to check for SSRF, and of course reasonable but cannot be easily overridden.

**Comment by jernst** [comment]
Once done, make smoke test work: `mastodon_api_mastodon_api.session.json` with `wordpress_mastodon.ubos.constellation.json`

**Comment by jernst** [comment]
According to @pfefferle:

> 1. Set the `WP_DEBUG` const to true and the Plugin adds a filter to allow localhost/internal request
> 2. Directly implement the filter, the plugin is using for local development: https://github.com/Automattic/wordpress-activitypub/blob/trunk/includes/debug.php

**Comment by jernst** [comment]
This works for the ActivityPub plugin, but apparently not for the Friends plugin.

**Comment by pfefferle** [comment]
Do you use both in one WordPress installation?

**Comment by jernst** [comment]
Currently the configuration is:

* WordPress in the default configuration
* but with permalinkstructure: `/%year%/%monthnum%/%day%/%postname%/`
* and plugins: `activitypub`, `enable-mastodon-apps`, `friends` and `webfinger`.

Do you think that makes sense?

Re SSRF, I found a brute-force workaround, adding this to `wp-config.php`:

```
if( function_exists( 'add_filter' )) {
    add_filter( 'http_request_host_is_external', function( $isExternal, $host ) { return true; }, 20, 2 );
}
```

**Comment by akirk** [comment]
Using the `http_request_host_is_external` filter seems like a reasonable way although I have to admit I miss the context of what exactly is not working. Is it ok now?

**Comment by jernst** [comment]
There are apparently various checks on various levels to guard against SSRF attacks, which makes it impossible, out of the box, to run FediTest tests inside a Linux container which uses addresses such as 192.168.0.0/16. The ActivityPub plugin apparently disables them for its own calls when `WP_DEBUG` is true, but the Friends plugin does not do the same thing. (I'm not saying it needs to, just found out with lots of printfs...) This `http_request_host_is_external` does seem to do the trick.

**Comment by akirk** [comment]
The difference to the ActivityPub plugin is that the Friends plugin [uses the `wp_http_validate_url()` function](https://github.com/akirk/friends/blob/a160b6144784915913b5a5157c3442586823dce6/includes/class-friends.php#L1297) which needs to be circumvented with the `http_request_host_is_external` filter.
