### ISSUE TITLE
ci pipeline does not work anymore

### ISSUE THREAD

**Issue by naturzukunft** [fediverse-devnet/feditest#404]
Hi there, i've integrated feditest v0.3 in my[ ci-pipeline](https://gitlab.com/linkedopenactors/rdf-pub/-/blob/feature/fixTheClient/.gitlab-ci.yml?ref_type=heads#L134) a few weeks ago.

Today i'm fixing things in my branch, to merge it back to "develop", but feditest fails with "weird" errors ;-)

[Command line output of ci-pipeline](https://gitlab.com/linkedopenactors/rdf-pub/-/jobs/8134481201)

The pipeline builds its environment from scratch every time. therefore, the environment should actually be stable. The errors indicate something else, as far as I can judge.

**Comment by jernst** [comment]
We made no recent changes to the version in the python repos, and the error does not look like it really touches any of our code.

**Comment by naturzukunft** [comment]
Tonight I remembered that I am using the latest python image. That could be a problem. Because it can change.

python:3.11.10 works
python:3.12.7 works
**python:3.13.0 fails**

**Comment by jernst** [comment]
So we can consider this to be solved. #405 will help further
