### ISSUE TITLE
Create a pluggable error reporter with a single default implementation

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#43]
Maybe the default implementation can emit TAP per #39.

**Comment by steve-bate** [comment]
Do you have thoughts about how to configure plugins like this? I'm assuming we don't want to put it in the test plan. There's a wide range of options: a separate config file, environment variables, command line arguments, full plugin frameworks, etcetera.

**Comment by jernst** [comment]
Actually what you did is good enough for now with `--tap`. We can reopen in the future if needed.
