### ISSUE TITLE
Create a reporter that emits HTML output that can be easily published on feditest.org

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#44]
Maybe a JSON file that can be processed by hugo and included in web pages with a custom hugo tag?

**Comment by jernst** [comment]
I think we want one HTML table per TestRun.

Within that table, we want a (first, header) row that enumerates the sessions/constellations in the TestRun. Constellations are probably the data the reader wants, the session itself doesn't have much. It many cases, there may be only one.

Within that table, we want a (first, header) column that lists all the tests that were being run. If two sessions ran the same test, it should be the same row.

All other cells in the table report on the outcome of test <row> with session/constellation <column>. Each cell could have a CSS class that indicates the outcome, and the content should be the error message (if any). Then we can use CSS to format the cells in different colors, like green for pass and red for fail, shorten text or even create overlay popups with full messages, or such.

P.S. It may be easier to generate the HTML directly than to go through JSON and/or hugo.

**Comment by steve-bate** [comment]
I'm going to do an initial prototype of this. It may be challenging to format given the test names are *much* longer than the short names in the example table.

**Comment by steve-bate** [comment]
I'm going to close this issue for the initial HTML generation. We can create other issues for report refinement.
