### ISSUE TITLE
Don't print exceptions when run without -v

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#78]
Which test failed why is good enough, we don't need all the exceptions unless the user requested that level of detail with `-v`.

**Comment by steve-bate** [comment]
I agree about AssertionErrors, but it seems like we'd still want exception stack traces related to framework/node issues or even non-assertion test errors (bugs, versus failing behavior).

**Comment by jernst** [comment]
Right!

**Comment by steve-bate** [comment]
We need to decide how we're going to handle various exception types that may or may not be a test failure versus test error.

**Comment by jernst** [comment]
On second thought, this is not very important, so I'm closing this. As we learn how to use FediTest, we may or may not reopen.
