### ISSUE TITLE
Create an implementation of FediverseNode that delegates to the Mastodon client API

### ISSUE THREAD

**Issue by jernst** [fediverse-devnet/feditest#94]
Let's call this `FediverseNode` subclass `MastodonClientApiNode`.

The first scenario would be something like this:

* Either modify `MastodonUbosNodeDriver` or create a version of `SaasFediverseNodeDriver` whose `_provision_node` instantiates `MastodonClientApiNode`.
* In `MastodonClientApiNode`, override `make_create_note` and use the Mastodon client API to actually make a `create` activity with a `Note` when invoked and return the URL of the created activity.
* Run a simplified version of `DeliverToInboxTest` to invoke `create_note` from a test.

If we can do this, we know we can do the rest of what this `MastodonClientApiNode` will have to do, too.

Some notes:

* `NodeDriver._provision_node` is being handed the `hostname` in its parameters if specified in the TestPlan file.
* How to get an oauth token is tbd. Is there a way to do this that:
  1. can be performed from behind the firewall, against a public Mastodon instance, without another cooperating public website? At all?
  1. ... and also can be scripted requiring no human intervention?
  1. If not, can it be automated against a locally running instance? (e.g. by invoking a script that runs a query against the Mastodon database; assume feditest has access to all relevant installation and db data including credentials)

**Comment by steve-bate** [comment]
I have an uncommited Mastodon node that works with a modified `AcceptFollowTest`. I'll wait to commit it until the test framework updates are complete and the tests are updated (so I can test the node more thoroughly).

**Comment by jernst** [comment]
We got that now, and we can create new issues for what's broken (by me, probably) or incomplete.
